import bcrypt from 'bcryptjs';

interface SeedProduct {
    description: string;
    images: string[];
    inStock: number;
    price: number;
    sizes: ValidSizes[];
    slug: string;
    tags: string[];
    title: string;
    type: ValidTypes;
    gender: 'men'|'women'|'kid'|'unisex'
}

interface SeedUser {
    name     : string;
    email    : string;
    password : string;
    role     : 'admin'|'client'
}

type ValidSizes = 'XS'|'S'|'M'|'L'|'XL'|'XXL'|'XXXL';
type ValidTypes = 'shirts'|'pants'|'hoodies'|'hats';



interface SeedData {
    users: SeedUser[];
    products: SeedProduct[];
}

export const initialData: SeedData = {
  users: [
    {
      name: 'Alfonso Admin',
      email: 'admin@ona.com',
      password: bcrypt.hashSync('123456'),
      role: 'admin',
    },
    {
      name: 'Alfonso Client',
      email: 'alfonso@gmail.com',
      password: bcrypt.hashSync('123456'),
      role: 'client',
    },
  ],
  products: [
    {
      description:
        'Shirt in a woven linen and cotton blend with a concealed button-down collar and classic button placket. Open chest pocket, yoke at back with box pleat, and long sleeves with adjustable buttoning at cuffs. Rounded hem. Slim fit - a modern fit with narrow shoulders and shaped waist for a tailored silhouette.',
      images: ['1740176-00-A_0_2000.jpg', '1740176-00-A_1.jpg'],
      inStock: 7,
      price: 29.99,
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      slug: 'mens_chill_crew_neck_sweatshirt',
      type: 'shirts',
      tags: ['sweatshirt'],
      title: 'Slim Fit Linen-blend Shirt',
      gender: 'men',
    },
    {
      description:
        'Regular-fit, short-sleeved polo shirt in terry. Collar, V-shaped opening at top, and an open chest pocket. Straight-cut hem with slit at sides.',
      images: ['1740507-00-A_0_2000.jpg', '1740507-00-A_1.jpg'],
      inStock: 5,
      price: 17.99,
      sizes: ['XS', 'S', 'M', 'XL', 'XXL'],
      slug: 'men_quilted_shirt_jacket',
      type: 'shirts',
      tags: ['jacket'],
      title: 'Regular Fit Terry Polo Shirt',
      gender: 'men',
    },
    {
      description:
        'Relaxed-fit shirt in a woven linen and cotton blend. Turn-down collar, classic button placket, and yoke at the back. Long sleeves with sleeve placket, link button, and button at cuffs. Open chest pocket and a gently rounded hem.',
      images: ['1740280-00-A_0_2000.jpg', '1740280-00-A_1.webp'],
      inStock: 50,
      price: 29.99,
      sizes: ['XS', 'S', 'M', 'L'],
      slug: 'men_turbine_long_sleeve_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Relaxed Fit Linen-blend Shirt',
      gender: 'men',
    },
    {
      description:
        "Introducing the Tesla Turbine Collection. Designed for style, comfort and everyday lifestyle, the Men's Turbine Short Sleeve Tee features a subtle, water-based Tesla wordmark across the chest and our T logo below the back collar. The lightweight material is double-dyed, creating a soft, casual style for ideal wear in any season. Made from 50% cotton and 50% polyester.",
      images: ['1741416-00-A_0_2000.jpg', '1741416-00-A_1.webp'],
      inStock: 50,
      price: 14.99,
      sizes: ['M', 'L', 'XL', 'XXL'],
      slug: 'men_turbine_short_sleeve_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Relaxed Fit Cotton T-shirt',
      gender: 'men',
    },
    {
      description:
        'Relaxed-fit shirt in a woven linen and cotton blend. Turn-down collar, classic button placket, and yoke at the back. Long sleeves with sleeve placket, link button, and button at cuffs. Open chest pocket and a gently rounded hem.',
      images: ['7654393-00-A_2_2000.jpg', '7654393-00-A_3.jpg'],
      inStock: 0,
      price: 29.99,
      sizes: ['M', 'L', 'XL', 'XXL'],
      slug: 'men_cybertruck_owl_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Relaxed Fit Linen-blend Shirt',
      gender: 'men',
    },
    {
      description: 'Slim-fit T-shirts in soft cotton jersey with a round neck.',
      images: ['1703767-00-A_0_2000.jpg', '1703767-00-A_1.jpg'],
      inStock: 15,
      price: 34.99,
      sizes: ['S', 'M', 'L', 'XL'],
      slug: 'men_solar_roof_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: '5-pack Slim Fit T-shirts',
      gender: 'men',
    },
    {
      description:
        "Inspired by the world’s most unlimited resource, the Let the Sun Shine Tee highlights our fully integrated home solar and storage system. Designed for fit, comfort and style, the tee features a sunset graphic along with our Tesla wordmark on the front and our signature T logo printed above 'Solar Roof' on the back. Made from 100% Peruvian cotton.",
      images: ['1700280-00-A_0_2000.jpg', '1700280-00-A_1.jpg'],
      inStock: 17,
      price: 17.99,
      sizes: ['XS', 'S', 'XL', 'XXL'],
      slug: 'men_let_the_sun_shine_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Muscle Fit Cotton Shirt',
      gender: 'men',
    },
    {
      description:
        'Short-sleeved shirt in a woven linen and cotton blend. Resort collar, buttons without placket, an open chest pocket, and yoke at back with darts. Straight-cut hem. Regular Fit – classic fit with good room for movement and a gently tapered waist for a comfortable, tailored silhouette.',
      images: ['8764734-00-A_0_2000.jpg', '8764734-00-A_1.jpg'],
      inStock: 12,
      price: 24.99,
      sizes: ['XS', 'S', 'M'],
      slug: 'men_3d_large_wordmark_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Regular Fit Linen-blend Shirt',
      gender: 'men',
    },
    {
      description:
        'Shirt in oxford cotton. Button-down collar, classic button placket, yoke at back, and open chest pocket. Long sleeves with button at cuffs and sleeve placket with link button. Gently rounded hem. Regular Fit – classic fit with good room for movement and gently tapered waist for a comfortable, tailored silhouette.',
      images: ['7652426-00-A_0_2000.jpg', '7652426-00-A_1.jpg'],
      inStock: 5,
      price: 24.99,
      sizes: ['XS', 'S'],
      slug: 'men_3d_t_logo_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Regular Fit Oxford Shirt',
      gender: 'men',
    },
    {
      description:
        'Polo shirt in a fine-knit modal and cotton blend. Ribbed collar, 1/4-zip, and short raglan sleeves. Muscle Fit – designed to showcase the body’s physique with narrow shoulders, tapered sleeves, and sharply tapered waist for a flattering silhouette.',
      images: ['8528839-00-A_0_2000.jpg', '8528839-00-A_2.jpg'],
      inStock: 2,
      price: 29.99,
      sizes: ['XS', 'S', 'M'],
      slug: 'men_3d_small_wordmark_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Muscle Fit Polo shirt',
      gender: 'men',
    },
    {
      description:
        'Long, relaxed-fit T-shirt in cotton slub jersey. Rounded, wider neckline with rolled raw edge, open chest pocket, and sewn cuffs on sleeves. Rounded hem at front. Longer at back.',
      images: ['1549268-00-A_0_2000.jpg', '1549268-00-A_2.jpg'],
      inStock: 82,
      price: 15.99,
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      slug: 'men_plaid_mode_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Long T-shirt',
      gender: 'men',
    },
    {
      description:
        'Oversized T-shirt in soft cotton jersey with a printed motif. Ribbed crew neck, dropped shoulders, and straight-cut hem.',
      images: ['9877034-00-A_0_2000.jpg', '9877034-00-A_2.jpg'],
      inStock: 24,
      price: 19.99,
      sizes: ['XL', 'XXL'],
      slug: 'men_powerwall_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Oversized Fit Printed T-shirt',
      gender: 'men',
    },
    {
      description:
        'Regular-fit polo shirt in a rib-knit viscose and cotton blend. Resort collar, short sleeves, and buttons at front.',
      images: ['1633802-00-A_0_2000.jpg', '1633802-00-A_2.jpg'],
      inStock: 5,
      price: 29.99,
      sizes: ['XS', 'S', 'XXL'],
      slug: 'men_battery_day_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Regular Fit Rib-knit Polo Shirt',
      gender: 'men',
    },
    {
      description:
        'Relaxed-fit T-shirt in soft cotton jersey with a printed design. Ribbed crew neck and dropped shoulders.',
      images: ['1740245-00-A_0_2000.jpg', '1740245-00-A_1.jpg'],
      inStock: 10,
      price: 17.99,
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      slug: 'men_raven_lightweight_hoodie',
      type: 'hoodies',
      tags: ['hoodie'],
      title: 'Relaxed Fit T-shirt',
      gender: 'men',
    },
    {
      description: 'Slim-fit, V-neck T-shirts in cotton jersey.',
      images: ['1740051-00-A_0_2000.jpg', '1740051-00-A_1.jpg'],
      inStock: 10,
      price: 38.99,
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      slug: 'chill_pullover_hoodie',
      type: 'hoodies',
      tags: ['hoodie'],
      title: '5-pack Slim Fit T-shirts',
      gender: 'unisex',
    },
    {
      description:
        'Short-sleeved shirt in a woven linen and cotton blend. Resort collar, buttons without placket, an open chest pocket, and yoke at back with darts. Straight-cut hem. Regular Fit – classic fit with good room for movement and a gently tapered waist for a comfortable, tailored silhouette.',
      images: ['1741111-00-A_0_2000.jpg', '1741111-00-A_1.jpg'],
      inStock: 100,
      price: 22.99,
      sizes: ['XS', 'L', 'XL', 'XXL'],
      slug: 'men_chill_full_zip_hoodie',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Regular Fit Linen-blend Shirt',
      gender: 'men',
    },
    {
      description:
        'Short-sleeved shirt in woven, stretch cotton fabric. Narrow band collar, classic button placket, and yoke and darts at back. Sewn cuffs on sleeves and rounded hem. Muscle Fit – designed to showcase physique. Narrow shoulders, gently tapered sleeves, and accentuated waist for a flattering silhouette.',
      images: ['1740140-00-A_0_2000.jpg', '1740140-00-A_1.jpg'],
      inStock: 7,
      price: 17.99,
      sizes: ['XS', 'S', 'M'],
      slug: 'men_chill_quarter_zip_pullover_-_gray',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Muscle Fit Cotton Shirt',
      gender: 'men',
    },
    {
      description:
        'Oversized T-shirt in soft cotton jersey with a printed pattern. Ribbed crew neck, dropped shoulders, and an open chest pocket. Straight-cut hem.',
      images: ['1740145-00-A_2_2000.jpg', '1740145-00-A_1.jpg'],
      inStock: 15,
      price: 17.99,
      sizes: ['XS', 'S', 'M', 'L'],
      slug: 'men_chill_quarter_zip_pullover_-_white',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Oversized Fit Patterned Cotton T-shirt',
      gender: 'men',
    },
    {
      description:
        'Relaxed-fit overalls in cotton twill. Adjustable suspenders with metal fasteners, metal buttons at sides, and mock fly. Two-part bib pocket, diagonal side pockets, and open back pockets. Hammer loop on one leg and pocket with two compartments on other leg.',
      images: ['8529107-00-A_0_2000.jpg', '8529107-00-A_1.jpg'],
      inStock: 15,
      price: 39.99,
      sizes: ['XS', 'S', 'XL', 'XXL'],
      slug: '3d_large_wordmark_pullover_hoodie',
      type: 'hoodies',
      tags: ['hoodie'],
      title: 'Overalls',
      gender: 'unisex',
    },
    {
      description:
        'A beautifully quilted finish lends endless dimension to this anorak, a water-resistant pick complete with a cozy hood.',
      images: ['7654420-00-A_0_2000.jpg', '7654420-00-A_1_2000.jpg'],
      inStock: 13,
      price: 79.99,
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      slug: 'cybertruck_graffiti_hoodie',
      type: 'hoodies',
      tags: ['hoodie'],
      title: "'Women's Hooded Quilted Anorak'",
      gender: 'unisex',
    },
    {
      description:
        'Bucket hat in cotton twill with a printed and embroidered motif at front. Sweatband and wide brim with adjustable chin strap.',
      images: ['1657932-00-A_0_2000.jpg', '1657932-00-A_1.jpg'],
      inStock: 11,
      price: 14.99,
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      slug: 'relaxed_t_logo_hat',
      type: 'hats',
      tags: ['hats'],
      title: 'Chin-strap Bucket Hat',
      gender: 'unisex',
    },
    {
      description:
        'Trucker cap with an embroidered motif at front. Adjustable plastic fastener at back.',
      images: ['1740417-00-A_0_2000.jpg', '1740417-00-A_1.jpg'],
      inStock: 13,
      price: 12.99,
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      slug: 'thermal_cuffed_beanie',
      type: 'hats',
      tags: ['hats'],
      title: 'Trucker Cap',
      gender: 'unisex',
    },
    {
      description:
        'Single-breasted blazer in a woven viscose blend. Notched lapels and two buttons at front. Welt front pockets, decorative button at cuffs, and vent at back. Lined.',
      images: ['1740535-00-A_0_2000.jpg', '1740535-00-A_1.jpg'],
      inStock: 85,
      price: 49.99,
      sizes: ['XS', 'S', 'M'],
      slug: 'women_cropped_puffer_jacket',
      type: 'hoodies',
      tags: ['hoodie'],
      title: 'Single-breasted Jacket',
      gender: 'women',
    },
    {
      description:
        'Oversized jacket in a woven linen and viscose blend. Notched lapels, defined, shoulders, and one button at front. Decorative chest pocket and welt front pockets with flap. Lined.',
      images: ['1740226-00-A_0_2000.jpg', '1740226-00-A_1.jpg'],
      inStock: 10,
      price: 59.99,
      sizes: ['XS', 'S', 'M', 'XXL'],
      slug: 'women_chill_half_zip_cropped_hoodie',
      type: 'hoodies',
      tags: ['hoodie'],
      title: 'Oversized Linen-blend Jacket',
      gender: 'women',
    },
    {
      description:
        'Soft, oversized sweatshirt jacket. Lined, drawstring hood, zipper at front, and kangaroo pockets. Dropped shoulders, long sleeves, and ribbing at cuffs and hem. Soft, brushed inside.',
      images: ['1740260-00-A_0_2000.jpg', '1740260-00-A_1.jpg'],
      inStock: 9,
      price: 29.99,
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      slug: 'women_raven_slouchy_crew_sweatshirt',
      type: 'hoodies',
      tags: ['hoodie'],
      title: 'Oversized Hooded Jacket',
      gender: 'women',
    },
    {
      description:
        'Sleeveless top in ribbed viscose jersey with a sweetheart neckline at front.',
      images: ['1740290-00-A_0_2000.jpg', '1740290-00-A_1.jpg'],
      inStock: 10,
      price: 24.99,
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      slug: 'women_turbine_cropped_long_sleeve_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Ribbed Top',
      gender: 'women',
    },
    {
      description:
        'Wide-cut shirt dress in cotton denim. Collar, buttons at front, and a chest pocket. Dropped shoulders and wide sleeves with button at cuffs.',
      images: ['1741441-00-A_0_2000.jpg', '1741441-00-A_1.jpg'],
      inStock: 0,
      price: 17.99,
      sizes: ['XS', 'S'],
      slug: 'women_turbine_cropped_short_sleeve_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Top Circle',
      gender: 'women',
    },
    {
      description:
        'Tank top in airy linen jersey with a round neckline straight-cut hem.',
      images: ['8765090-00-A_0_2000.jpg', '8765090-00-A_1.jpg'],
      inStock: 30,
      price: 14.99,
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      slug: 'women_t_logo_short_sleeve_scoop_neck_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Linen Jersey Tank Top',
      gender: 'women',
    },
    {
      description:
        "A boho-chic top for your skirts, jeans and more, Free People's Hailey features shadow stripes for subtle detail.",
      images: ['8765100-00-A_0_2000.jpg', '8765100-00-A_1.jpg'],
      inStock: 16,
      price: 22.99,
      sizes: ['XS', 'S', 'L', 'XL', 'XXL'],
      slug: 'women_t_logo_long_sleeve_scoop_neck_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Hailey Cotton Shadow-Striped Crop Top',
      gender: 'women',
    },
    {
      description:
        'Floral prints bring feminine flair to your wardrobe along with the eye-catching sleeves on this Vince Camuto blouse.',
      images: ['8765120-00-A_0_2000.jpg', '8765120-00-A_1.jpg'],
      inStock: 18,
      price: 18.99,
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      slug: 'women_small_wordmark_short_sleeve_v-neck_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Floral Smocked Puffed Sleeve Blouse',
      gender: 'women',
    },
    {
      description:
        'Keep your casual essentials fresh and ready when you need them in this relaxed crewneck top by Alfani.',
      images: ['8765115-00-A_0_2000.jpg', '8765115-00-A_1.jpg'],
      inStock: 5,
      price: 15.99,
      sizes: ['XL', 'XXL'],
      slug: 'women_large_wordmark_short_sleeve_crew_neck_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Crewneck T-Shirt',
      gender: 'women',
    },
    {
      description:
        'Curate a wardrobe that can transition through the seasons with this 3/4-sleeve top from JM Collection.',
      images: ['1549275-00-A_0_2000.jpg', '1549275-00-A_1.jpg'],
      inStock: 16,
      price: 24.99,
      sizes: ['S', 'M'],
      slug: 'women_plaid_mode_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Printed 3/4-Sleeve Tunic',
      gender: 'women',
    },
    {
      description:
        'Rock a workweek-inspired style in this slim-fit tweed jacket from BCBGeneration designed with a point collar and two front pockets.',
      images: ['9877040-00-A_0_2000.jpg', '9877040-00-A_1.jpg'],
      inStock: 10,
      price: 30.99,
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      slug: 'women_powerwall_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Tweed Jacket',
      gender: 'women',
    },
    {
      description:
        'A fresh take on the peasant top, this Free People style features a modern neckline and puffed sleeves.',
      images: ['5645680-00-A_0_2000.jpg', '5645680-00-A_3.jpg'],
      inStock: 3,
      price: 29.99,
      sizes: ['M', 'L', 'XL', 'XXL'],
      slug: 'women_corp_jacket',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Penelope T-Shirt',
      gender: 'women',
    },
    {
      description:
        "Super flirty with a cropped length and tied details, Free People's Kitty top finishes with soft puffed sleeves.",
      images: ['1740270-00-A_0_2000.jpg', '1740270-00-A_1.jpg'],
      inStock: 162,
      price: 17.99,
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      slug: 'women_raven_joggers',
      type: 'shirts',
      tags: ['shirt'],
      title: "Women's Kitty Cotton Front-Tie Crop Top",
      gender: 'women',
    },
    {
      description:
        'A fun lace-up detail adds plenty of style to her active aesthetic with this cute Ideology T-shirt.',
      images: ['1742694-00-A_1_2000.jpg', '1742694-00-A_3.jpg'],
      inStock: 10,
      price: 10.99,
      sizes: ['XS', 'S', 'M'],
      slug: 'kids_cybertruck_long_sleeve_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Big Girls Core Lace-Up T-Shirt',
      gender: 'kid',
    },
    {
      description:
        "This jersey T-shirt is washed for added softness, making it a comfortable essential he'll want to wear again and again.",
      images: ['8529312-00-A_0_2000.jpg', '8529312-00-A_1.jpg'],
      inStock: 0,
      price: 15.99,
      sizes: ['XS', 'S', 'M'],
      slug: 'kids_scribble_t_logo_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Big Boys Cotton Jersey Crewneck T-Shirt',
      gender: 'kid',
    },
    {
      description:
        'The Kids Cybertruck Tee features the iconic Cybertruck graffiti wordmark and is made from 100% Peruvian cotton for maximum comfort.',
      images: ['8529342-00-A_0_2000.jpg', '8529342-00-A_1.jpg'],
      inStock: 10,
      price: 14.99,
      sizes: ['XS', 'S', 'M'],
      slug: 'kids_cybertruck_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Toddler Boys Solid Basic Tee',
      gender: 'kid',
    },
    {
      description:
        'This comfy and soft basic T-shirt by Epic Threads is a wardrobe staple.',
      images: ['8529354-00-A_0_2000.jpg', '8529354-00-A_1.jpg'],
      inStock: 10,
      price: 13.99,
      sizes: ['XS', 'S', 'M'],
      slug: 'kids_racing_stripe_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Little Girls Solid Basic T-shirt',
      gender: 'kid',
    },
    {
      description: 'Super soft basic tee is a must have by Epic Threads.',
      images: ['7652465-00-A_0_2000.jpg', '7652465-00-A_1.jpg'],
      inStock: 10,
      price: 12.99,
      sizes: ['XS', 'S', 'M'],
      slug: 'kids_3d_t_logo_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Little Boys Solid Basic Tee',
      gender: 'kid',
    },
    {
      description:
        'This comfy and soft basic t-shirt by Epic Threads is a wardrobe staple.',
      images: ['100042307_0_2000.jpg', '100042307_alt_2000.jpg'],
      inStock: 10,
      price: 18.99,
      sizes: ['XS', 'S', 'M'],
      slug: 'kids_checkered_tee',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Big Boys Solid Basic Tee',
      gender: 'kid',
    },
    {
      description:
        'A colorful graphic adds fun to this comfy and cool top from Ideology.',
      images: ['1473809-00-A_1_2000.jpg', '1473809-00-A_alt.jpg'],
      inStock: 16,
      price: 15.99,
      sizes: ['XS', 'S'],
      slug: 'made_on_earth_by_humans_onesie',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Big Girls Fearless Top',
      gender: 'kid',
    },
    {
      description:
        'Caged accents and pops of color detail the sides of these stretchy leggings by Ideology.',
      images: ['8529387-00-A_0_2000.jpg', '8529387-00-A_1.jpg'],
      inStock: 0,
      price: 19.99,
      sizes: ['XS', 'S'],
      slug: 'scribble_t_logo_onesie',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Big Girls Caged-Hem Leggings',
      gender: 'kid',
    },
    {
      description:
        'Stretchy and comfy in a high-waisted design, these full-length Ideology active leggings are versatile for her active days.',
      images: ['1473834-00-A_2_2000.jpg', '1473829-00-A_2_2000.jpg'],
      inStock: 10,
      price: 13.99,
      sizes: ['XS', 'S'],
      slug: 'zero_emissions_(almost)_onesie',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Big Girl Core Stretch Leggings',
      gender: 'kid',
    },
    {
      description:
        'Hit the slopes with the dinos in this graphic T-shirt from Epic Threads that will bring a smile to your face.',
      images: ['1742702-00-A_0_2000.jpg', '1742702-00-A_1.jpg'],
      inStock: 10,
      price: 15.99,
      sizes: ['XS', 'S', 'M'],
      slug: 'kids_cyberquad_bomber_jacket',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Toddler Boys Graphic T-shirt',
      gender: 'kid',
    },
    {
      description:
        'Camo tees are an essential part of any wardrobe. A camo print brings an updated feel to this soft basic tee from Epic Threads.',
      images: ['1506211-00-A_0_2000.jpg', '1506211-00-A_1_2000.jpg'],
      inStock: 10,
      price: 13.99,
      sizes: ['XS', 'S', 'M'],
      slug: 'kids_corp_jacket',
      type: 'shirts',
      tags: ['shirt'],
      title: 'Toddler Boys Camo Basic Tee',
      gender: 'kid',
    },
  ],
};