name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.17

    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
        